import React from "react";
import PropTypes from "prop-types";

import MenuPanel from "terriajs/lib/ReactViews/StandardUserInterface/customizable/MenuPanel.jsx";
import PanelStyles from "terriajs/lib/ReactViews/Map/Panels/panel.scss";
import Styles from "./related-maps.scss";
import classNames from "classnames";

function RelatedMaps(props) {
  const dropdownTheme = {
    inner: Styles.dropdownInner,
    icon: "gallery"
  };

  return (
    <MenuPanel
      theme={dropdownTheme}
      btnText="Related Maps"
      smallScreen={props.smallScreen}
      viewState={props.viewState}
      btnTitle="See related maps"
      showDropdownInCenter
    >
      <div className={classNames(PanelStyles.header)}>
        <label className={PanelStyles.heading}>Related Maps</label>
      </div>

      <p>Clicking on a map below will open it in a separate window or tab.</p>

      <div className={classNames(PanelStyles.section, Styles.section)}>
        <a target="_blank" href="https://indiawris.gov.in/wris/#/home">
          <img
            className={Styles.image}
            src={require("../../wwwroot/images/india-wris.jpg")}
            alt="India-WRIS"
          />
        </a>

        <a
          target="_blank"
          className={Styles.link}
          href="https://indiawris.gov.in/wris/#/home"
        >
          India-WRIS
        </a>

        <p>
          India-WRIS WebGIS aims as a ‘Single Window’ solution for
          comprehensive, authoritative and consistent data & information of
          India’s water resources along with allied natural resources in a
          standardized national GIS framework with tools to search, access,
          visualize, understand and analyze the data for assessment, monitoring,
          planning, development and finally Integrated Water Resources
          Management (IWRM).
        </p>
      </div>

      <div className={classNames(PanelStyles.section, Styles.section)}>
        <a target="_blank" href="https://data.apps.fao.org/aquamaps/">
          <img
            className={Styles.image}
            src={require("../../wwwroot/images/fao-aquamap.jpg")}
            alt="Northern Australia"
          />
        </a>

        <a
          target="_blank"
          className={Styles.link}
          href="https://data.apps.fao.org/aquamaps/"
        >
          FAO AQUAMAPS
        </a>

        <p>
          AQUAMAPS is AQUASTAT’s online geospatial database on water and
          agriculture. Through a sophisticated web platform, regional and global
          spatial datasets on water resources and water management, produced by
          FAO and by external data providers, are made accessible. <br />
          AQUAMAPS is complementary to AQUASTAT’s statistical data. AQUAMAPS
          concentrates on geographical information that for the biggest part has
          been generated by spatial modelling. AQUASTAT’s statistical
          information has been used to calibrate and validate the results.
          <a
            target="_blank"
            className={Styles.link}
            href="https://data.apps.fao.org/aquamaps/"
          >
            AQUAMAPS
          </a>
          .
        </p>
      </div>
    </MenuPanel>
  );
}

RelatedMaps.propTypes = {
  viewState: PropTypes.object.isRequired,
  smallScreen: PropTypes.bool
};

export default RelatedMaps;
